name = "medium-clone"
compatibility_date = "2024-03-07"
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTk0OTFmMjktN2JjZS00MzRkLWI3MmItNzI0NDhjMWQwNTc0IiwidGVuYW50X2lkIjoiZTU5N2M2Nzg5OWVkNDRkM2NhMjNjZDc1ODJhNjQ4MmQ4MmYwZjY5YjgyZjBmMTQ1MTlkYTk5ODk2OTVhZTM3OSIsImludGVybmFsX3NlY3JldCI6IjdlYmU2M2Q4LTY2NmUtNDZkZi1iNTFmLWZmNGUxMThhZjkxNiJ9.YaLV2u8r6YN0wIoTcuu09hJzz07-Jw3rH9O7viqeQNo"
JWT_SECRET="RANDOM_STRING"
